# Generated by Django 4.0.4 on 2022-06-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_cbirthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cLine',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
