# Generated by Django 4.0.4 on 2022-06-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_cline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cLine',
            new_name='cLine1',
        ),
    ]
